### ISSUE TITLE
.NET configuration is not in the Helm Cart

### ISSUE THREAD

**Issue by kuisathaverat** [elastic/apm-mutating-webhook#41]
The configuration setting for the `.NET` agent does not have defaults in the Helm Chart, it makes not possible to configure `image` and `artifact` , there are no references to a possible values for those parameters in the documentation.

**Comment by kuisathaverat** [comment]
the `docker.elastic.co/observability/apm-agent-dotnet:latest` Docker file does not exist.

**Comment by felixbarny** [comment]
.NET is not supported at the moment. I have removed some references in the docs. If there are more that I have missed, please let me know.
