### ISSUE TITLE
The Helm Chart is not published as Helm Chart

### ISSUE THREAD

**Issue by kuisathaverat** [elastic/apm-mutating-webhook#43]
The current Helm Chart was not published on any Helm Chart repository, nor the git repository is not a Helm Chart repository. It makes the only way to install the helm chart is by cloning the Git repository and launching Helm using the Helm Chart folder as Helm Chart.

**Comment by simitt** [comment]
related https://github.com/elastic/apm-mutating-webhook/issues/6

**Comment by simitt** [comment]
Closing this issue as being duplicated and tackled in #6 .
