### ISSUE TITLE
Distribute the helm chart

### ISSUE THREAD

**Issue by stuartnelson3** [elastic/apm-mutating-webhook#6]
Align with the elastic helm chart strategy (common vs. separate repos?). Should users just clone the repo and use the folder within the repo?

**Comment by marclop** [comment]
We've got a shared https://github.com/elastic/helm-charts which seems to be where we use to publish stack helm charts. Even though the Stack helm charts seem to not be supported going forward, the ECK helm chart seems like it is not going anywhere.

I'm looking into how the ECK helm charts are published and what we need to do that.

**Comment by marclop** [comment]
I've released a dev version of the mutating webhook and it seems to be accessible:

```console
$ helm repo add elastic-dev https://helm-dev.elastic.co
"elastic-dev" has been added to your repositories
$ helm install dev-mut-wh elastic-dev/apm-agent-auto-attach
NAME: dev-mut-wh
LAST DEPLOYED: Thu Sep  8 14:15:09 2022
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
$ helm list
NAME      	NAMESPACE	REVISION	UPDATED                              	STATUS  	CHART                      	APP VERSION
dev-mut-wh	default  	1       	2022-09-08 14:15:09.545791 +0800 WITA	deployed	apm-agent-auto-attach-0.1.0
```

As part of this issue we should also update the docs as well to indicate that a manual creation of a tag, release and trigger of the publishing job is necessary for the helm chart to be published.

**Comment by felixbarny** [comment]
@kuisathaverat does this unblock you to use the webhook in our demo environment?

**Comment by kuisathaverat** [comment]
@felixbarny We deploy the Helm chart manually by making a Git clone and helm install, It is already deployed and working for about 2 months. This will make the deploy easier only using Helm.

**Comment by felixbarny** [comment]
Good question. I don't have a strong opinion either way. Are we deploying snapshot APM Servers in the demo environments? I think we do, right? So that might speak in favor of using snapshots of the webhook, too. However, IINM, we're not deploying agent snapshots currently.

**Comment by simitt** [comment]
The k8s webhook does not follow the stack release versions, so we don't actually have `SNAPSHOTS` in that sense. What might still proof valuable in the future is to deploy pre-release helm charts that are released to the https://helm-dev.elastic.co. WDYT?

**Comment by kuisathaverat** [comment]
>Good question. I don't have a strong opinion either way. Are we deploying snapshot APM Servers in the demo environments? I think we do, right? 

yes

>So that might speak in favor of using snapshots of the webhook, too. However, IINM, we're not deploying agent snapshots currently.

It is not needed. We can use commit SHA or tags to grab a particular webhook version. About the APM Agent SNAPSHOTs 
recently comes the topic again, there is a request in progress to deploy APM Agents SNAPSHOT to test the Opbean, so at some point, I think we would need to release those SNAPSHOT for internal use.

>The k8s webhook does not follow the stack release versions, so we don't actually have SNAPSHOTS in that sense. 

It is not a matter of publish the SNAPSHOTs (we will use the manual deployment for this case). It is a matter of what we need to deploy on the oblt clusters, Releases or SNAPSHOTs?

**Comment by marclop** [comment]
Since the helm chart publisher works by using GitHub releases, we'd have to tag / do draft releases every time we want to test a pre-release version. Alternatively, we could still test and use pre-releases if we clone the repo's main branch and install the chart from its folder directly, which may be a much simpler and convenient workflow, since it won't pollute the GitHub releases as much.

**Comment by felixbarny** [comment]
Maybe we could do daily (if there have been any changes) snapshot releases from the repo and publish to https://helm-dev.elastic.co. That's similar to what we do for the Java agent.

However, I think that can come later. Let's maybe start with just testing releases.

**Comment by kuisathaverat** [comment]
>However, I think that can come later. Let's maybe start with just testing releases.

We are testing SNAPSHOTs right now, the version used is the version taken from the repo when we trigger an update of a cluster.

**Comment by marclop** [comment]
I re-published the `apm-attacher` chart version 0.1.0 in `https://helm-dev.elastic.co`.

**Comment by simitt** [comment]
@kuisathaverat using the latest available version from `https://helm-dev.elastic.co` sounds reasonable to me. We can then figure out and adapt the cadence when we want to push helm charts there. @kuisathaverat does that work for you?

**Comment by kuisathaverat** [comment]
> @kuisathaverat does that work for you?

sure

**Comment by simitt** [comment]
If I am not missing anything here, then I believe we can close this issue. The first helm chart has been distributed and they will be released by creating release tags in this repo.
